shellEmulator: true
trustPolicy: no-downgrade

allowBuilds:
  esbuild: true
  simple-git-hooks: true

catalog:
  '@adobe/jsonschema2md': ^8.0.10
  '@antfu/eslint-config': ^7.7.0
  '@types/node': ^25.4.0
  bumpp: ^10.4.1
  yaml-eslint-parser: ^2.0.0
  eslint: ^10.0.3
  esno: ^4.8.0
  jsonc-eslint-parser: ^3.1.0
  nano-staged: ^0.9.0
  premove: ^4.0.0
  serve: ^14.2.0
  simple-git-hooks: ^2.13.1
  taze: ^19.10.0
  tsdown: ^0.21.1
  typescript: ^5.9.3
  zod: ^4.3.6
