shellEmulator: true
trustPolicy: no-downgrade

allowBuilds:
  esbuild: true
  simple-git-hooks: true

catalog:
  '@adobe/jsonschema2md': ^8.0.10
  '@types/node': ^25.5.0
  bumpp: ^11.0.1
  eslint: ^10.0.3
  esno: ^4.8.0
  nano-staged: ^0.9.0
  premove: ^4.0.0
  serve: ^14.2.6
  simple-git-hooks: ^2.13.1
  taze: ^19.10.0
  tsdown: ^0.21.4
  typescript: ^5.9.3
  zod: ^4.3.6
