import { z } from 'zod'
import { MANIFEST_SCHEMA_URL } from './constants'
import { RegistryLibraryItem } from './registry/item'
import { RegistryLibrary } from './registry/library'
import { RegistrySchema } from './registry.schema'

/**
 * Weme UI manifest schema.
 *
 * This schema is generated by `pnpm dlx @weme-ui/weme-ui add` command, DO NOT edit it manually.
 */
export const ManifestSchema = z
  .object({
    /**
     * Schema URL.
     *
     * @default {@link MANIFEST_SCHEMA_URL}
     */
    $schema: z
      .url()
      .trim()
      .default(MANIFEST_SCHEMA_URL)
      .meta({
        title: 'Manifest Schema URL',
        description: `The Schema URL, which should be \`${MANIFEST_SCHEMA_URL}\``,
        examples: [MANIFEST_SCHEMA_URL],
      }),

    /**
     * Added items
     */
    items: z
      .array(
        RegistryLibraryItem.safeExtend({
          /**
           * The registry name of the item
           */
          registry: RegistrySchema.pick({ name: true }),
          /**
           * The library name of the item
           */
          library: RegistryLibrary.pick({ name: true }),
          /**
           * The version of the registry
           */
          version: RegistrySchema.pick({ version: true }),
          /**
           * The hash of the registry
           */
          hash: RegistrySchema.pick({ hash: true }),
        }),
      )
      .meta({
        title: 'Manifest Items',
        description: 'The items in the manifest.',
      }),
  })
  .meta({
    $id: MANIFEST_SCHEMA_URL,
    title: 'Weme UI Manifest JSON Schema Definitions (v3)',
    description: 'This schema defines the structure of the manifest JSON file used in Weme UI.',
  })
