import { z } from 'zod'
import { MANIFEST_SCHEMA_URL } from './constants'
import { RegistryItemFileType, RegistryItemScope } from './registry'

/**
 * Manifest item file schema, which represents a file in the manifest item.
 */
export const ManifestItemFile = z.object({
  /**
   * File type
   */
  type: RegistryItemFileType,

  /**
   * File source
   *
   * @example 'https://raw.githubusercontent.com/weme-ui/weme-ui/refs/heads/main/registry/std/components/button/button.vue'
   */
  source: z.url().trim().meta({
    title: 'Manifest Item File Source',
    description: 'The source of the manifest item file.',
  }),

  /**
   * File destination
   *
   * @example '~/components/ui/button/button.vue'
   */
  dest: z.string().trim().meta({
    title: 'Manifest Item File Destination',
    description: 'The destination of the manifest item file.',
  }),

  /**
   * File hash (Local)
   */
  hash: z.string().trim().meta({
    title: 'Manifest Item File Hash',
    description: 'The hash of the manifest item file.',
  }),
}).meta({
  title: 'Manifest Item File',
  description: 'A file in the manifest item.',
})

/**
 * Manifest item schema, which represents an item in the manifest.
 */
export const ManifestItem = z.object({
  /**
   * Item name
   *
   * @example 'button'
   */
  name: z.string().lowercase().trim().meta({
    title: 'Manifest Item Name',
    description: 'The name of the manifest item.',
  }),

  /**
   * Item scope
   */
  scope: RegistryItemScope,

  /**
   * Item files
   */
  files: z.array(ManifestItemFile).meta({
    title: 'Manifest Item Files',
    description: 'The files of the manifest item.',
  }),
}).meta({
  title: 'Manifest Item',
  description: 'An item in the manifest.',
})

/**
 * Weme UI manifest schema.
 * This schema is generated by `weme-ui add` command, DO NOT edit it manually.
 */
export const ManifestSchemaV2 = z.object({
  /**
   * Schema URL.
   *
   * @default 'https://weme-ui.github.io/schema/v2/manifest.schema.json'
   */
  $schema: z.url().trim().default(MANIFEST_SCHEMA_URL).meta({
    title: 'Manifest Schema URL',
    description: `The Schema URL, which should be \`${MANIFEST_SCHEMA_URL}\``,
  }),

  /**
   * Last update time of the manifest.
   */
  lastUpdate: z.iso.datetime({ precision: 3 }).meta({
    title: 'Last Update',
    description: 'The last update time of the manifest.',
  }),

  /**
   * Manifest items
   */
  items: z.array(ManifestItem).meta({
    title: 'Manifest Items',
    description: 'The items in the manifest.',
  }),
}).meta({
  $id: MANIFEST_SCHEMA_URL,
  title: 'Weme UI Manifest JSON Schema Definitions',
  description: 'This schema defines the structure of the manifest JSON file used in Weme UI.',
})

export type ManifestSchema = z.infer<typeof ManifestSchemaV2>
