import { z } from 'zod'
import { MANIFEST_SCHEMA_URL } from '../constants'
import { SafeUrl } from '../shared'
import { AddedItem } from './item'

/**
 * Weme UI manifest schema.
 *
 * This schema is generated by `pnpm dlx @weme-ui/weme-ui add` command, DO NOT edit it manually.
 *
 * @see {@link MANIFEST_SCHEMA_URL}
 */
export const ManifestSchema = z
  .object({
    /**
     * Schema URL.
     *
     * @default {@link MANIFEST_SCHEMA_URL}
     */
    $schema: SafeUrl.default(MANIFEST_SCHEMA_URL).meta({
      title: 'Manifest Schema URL',
      description: `The Schema URL, which should be \`${MANIFEST_SCHEMA_URL}\``,
      examples: [MANIFEST_SCHEMA_URL],
    }),

    /**
     * Added items
     */
    items: z.array(AddedItem).optional().meta({
      title: 'Added Items',
      description: 'The added items in the project.',
    }),
  })
  .meta({
    $id: MANIFEST_SCHEMA_URL,
    title: 'Weme UI Manifest JSON Schema Definitions (v3)',
    description: 'This schema defines the structure of the manifest JSON file used in Weme UI.',
  })
